### PR TITLE
Fix non-root unpacking for old systems

### LINKED ISSUE #9: Cannot run `rspm::enable()` unless root
Hi Iñaki,

I just installed rspm on an Amazon Linux 2 cloud desktop and it's working a charm. System deps and package binaries all handled without a hitch. Thank you!

The one catch I'm running into is that I'm being forced to run R as root for it to work. Launching a plain `R` session yields the following error:

```r
> rspm::enable()
Downloading and installing required utilities...
Loaded plugins: priorities
You need to be root to perform this command.
error: File not found by glob: *
Error: something went wrong, utilities not available
```

The same command (and subsequent package installs) carry through without a problem if start a `sudo R` session.

While it's not the worst problem in the world---and any R packages installed during a sudo session are obviously available to my regular user after the fact---I was surprised by this root requirement. I thought everything was installed into the user home. Do you think it's an artifact of the federated user setup we have in these cloud environments? Any troubleshooting tips would be greatly appreciated.

P.S. I'm running the latest CRAN version of **rspm** (0.2.1).

### PR DESCRIPTION
**Pull request by Enchufa2**
@grantmcdermott @philipp-baumann: Could you please try this branch?

Closes #9

### CODE REVIEW

**Comment by philipp-baumann** [comment]
awesome, this PR works on Rocky 8.7 with RPM version 4.14.3. On CentOS like systems with RPM v < 4.12, can cpio be expected to be installed? If no, would a short error message to install help users?

**Comment by Enchufa2** [comment]
> works o

Thanks for testing. Package cpio is expected to be available because the CentOS 7 base image has this installed, even the docker one. And I believe they implemented rpm2archive to avoid providing cpio by default. Anyways, if this is not available, an error would be issued due to https://github.com/Enchufa2/rspm/pull/11/files#diff-da37bec44282a8b2a2f78b5040c8f5d211affb10a0727d08c9a8a784c32dacf2R21

**Comment by philipp-baumann** [comment]
> Thanks for testing. Package cpio is expected to be available because the CentOS 7 base image has this installed, even the docker one. And I believe they implemented rpm2archive to avoid providing cpio by default. Anyways, if this is not available, an error would be issued due to https://github.com/Enchufa2/rspm/pull/11/files#diff-da37bec44282a8b2a2f78b5040c8f5d211affb10a0727d08c9a8a784c32dacf2R21

Excellent, thanks a lot for this! Interesting note on rpm2archive.

**Comment by Enchufa2** [comment]
I'll merge this later and send it to CRAN. Thanks again for raising this.

**Pull request merged**
